// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Email struct {
	Uuid        uuid.UUID
	ToEmail     string
	Subject     string
	Body        string
	Type        string
	Status      string
	Attempts    int32
	MaxAttempts int32
	ErrorMsg    sql.NullString
	SentAt      sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	Uuid      uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSession struct {
	Uuid         uuid.UUID
	UserUuid     uuid.UUID
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}
